### ISSUE TITLE
Error when running az container app up

### ISSUE THREAD

**Issue by lrcuwicRSG1** [Azure/deploy-to-azure-cli-extension#52]
## Describe the bug

**Command Name**
`az container app up
Extension Name: deploy-to-azure. Version: 0.2.0.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/christoph/.azure/cliextensions/deploy-to-azure/azext_deploy_to_azure/dev/aci/up.py", line 78, in aci_up
    workflow_files = get_yaml_template_for_repo(acr_details, repo_name, port)
  File "/home/christoph/.azure/cliextensions/deploy-to-azure/azext_deploy_to_azure/dev/aci/up.py", line 135, in get_yaml_template_for_repo
    .replace(ACR_PLACEHOLDER, acr_details['name'])
TypeError: 'NoneType' object is not subscriptable

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az container app up`

## Environment Summary
```
Linux-5.4.0-1055-azure-x86_64-with-debian-10.2 (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.27.0

Extensions:
deploy-to-azure 0.2.0
ai-examples 0.2.5
ssh 0.1.5

```

**Comment by lrcuwicRSG1** [comment]
I have found the problem: The error occures when no azure container registry is available. If at least one acr is created, the script runs correctly.
